# Includes the sx1262 drivers and supporting modules if the compiled project 
# uses the netdev module
ifneq (,$(filter netdev,$(USEMODULE)))
  USEMODULE += sx1262
  USEMODULE += sx126x_dio2
  USEMODULE += sx126x_dio3
endif

# Includes the common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
