# ifneq (,$(filter netdev_default,$(USEMODULE)))
# endif
USEMODULE += sx1262
USEMODULE += sx126x_dio2
USEMODULE += sx126x_dio3

USEMODULE += boards_common_adafruit-nrf52-bootloader

include $(RIOTBOARD)/common/nrf52/Makefile.dep
include $(RIOTBOARD)/common/makefiles/stdio_cdc_acm.dep.mk
