# set programming environment
PROGRAMMER ?= uf2conv
PROGRAMMERS_SUPPORTED += uf2conv
# Drop the softdev partition (used for arduino and micropython, not required)
UF2_SOFTDEV ?= DROP

# Include common nrf52 configurations
include $(RIOTBOARD)/common/nrf52/Makefile.include
